---
- name: Update Server
  apt: update_cache=yes

- name: add docker apt key
  apt_key:
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D

- name: add docker apt repository
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo ubuntu-trusty main
    update_cache: yes

- name: install docker
  apt:
    name: docker-engine

- name: add ubuntu to docker group
  user:
    name: ubuntu
    groups: docker
    append: yes

- name: Start Docker 
  service: name=docker state=restarted

